#!/bin/bash
 
### BEGIN INIT INFO
# Provides:          graphite
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the graphite uwsgi app server
# Description:       starts graphite app server using start-stop-daemon
### END INIT INFO
 
PATH=/opt/uwsgi:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/uwsgi
 
OWNER=_graphite
 
NAME=uwsgi
DESC=uwsgi
 
test -x $DAEMON || exit 0
 
# Include uwsgi defaults if available
if [ -f /etc/default/uwsgi-graphite ] ; then
. /etc/default/uwsgi-graphite
fi
 
set -e
 
APPNAME=graphite
BASEPATH=/var/lib/graphite
PIDFILE=$BASEPATH/graphite.pid
 
DAEMON_OPTS="$VENV_ARG --ini /usr/share/graphite-web/graphite.ini --stats /tmp/uwsgi-stats-${APPNAME}.sock --need-app --lazy --master --pidfile $PIDFILE --daemonize $BASEPATH/graphite.log"
 
function do_start {
        start-stop-daemon --start --pid $PIDFILE --chuid $OWNER:$OWNER --user $OWNER --exec $DAEMON -- $DAEMON_OPTS
}
 
function do_stop {
        start-stop-daemon --signal QUIT --pid $PIDFILE --user $OWNER --quiet --retry 2 --stop  --oknodo
}
case "$1" in
  start)
        echo -n "Starting $DESC: "
        do_start
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        do_stop
        echo "$NAME."
        ;;
  restart)
        echo -n "Restarting $DESC: "
        do_stop
        sleep 1
        do_start
        echo "$NAME."
        ;;
  status)
        killall -10 $DAEMON
        ;;
      *)
            N=/etc/init.d/$NAME
            echo "Usage: $N {start|stop|restart|reload|force-reload|status}" >&2
            exit 1
            ;;
    esac
    exit 0